@extends('_layout.main')

@section('content')
    @include('components.page-indicator', [
        'page' => 'Security',
        'path' => ['Home', 'Security'],
    ])
    <section class="my-6 w-full flex flex-col lg:flex-row gap-6">

        @if ($user->twoFactorCode)
            <div class="w-full">
                <div class="bg-black rounded-lg overflow-hidden">
                    <div class="p-6 text-white/70 border-b border-white/25">
                        <p>Two Factor Setup</p>
                    </div>
                    @include('components.verified', [
                        'label' => '2FA Enabled',
                        'description' => 'Your 2FA suucessfull Enabled',
                    ])
                </div>
            </div>
        @else
            <div class="w-full">
                <div class="bg-black rounded-lg overflow-hidden">
                    <div class="p-6 text-white/70 border-b border-white/25">
                        <p>Two Factor Setup</p>
                    </div>
                    <div class="text-white/70 p-6 text-sm">
                        <p>To setup two factor authentication you first need to download Google Authenticator:</p>

                        <div class="my-4 flex flex-col">
                            <a href="" class="hover:text-blue-400">
                                <i class="bi bi-android2"></i>
                                Google Authenticator for Android (PlayStore)
                            </a>
                            <a href="" class="hover:text-blue-400 mt-4">
                                <i class="bi bi-apple"></i>
                                Google Authenticator for iOS (Apple App Store)
                            </a>
                        </div>

                        <p>
                            Then scan the below barcode or, if you are not able to scan the barcode, you can enter the
                            "Security Key" manually.
                        </p>

                        <p class="text-2xl mt-4">
                            Security Key: <span class="text-blue-400"> {{ $secretkey }} </span>(Time Based Code)
                        </p>

                        <div class="my-4">
                            {!! $qrcode !!}
                        </div>

                        <p class="lmy-2">
                            Enter the 6 digit code generated by Google Authenticator in the 2FA Code box and switch
                            "Enable
                            Two-Factor" to On
                        </p>

                        <p class="my-6 lg:my-4">
                            <span class="bg-red-500 px-2 text-white rounded-md">Important</span>
                            Save this secret code for future reference
                        </p>

                        <p class="my-2">
                            Note: No Google account is required to use Google Authenticator; skip any Google logins
                        </p>
                    </div>
                </div>
            </div>

            <div class="w-full">
                <div class="w-full rounded-lg overflow-hidden bg-black">
                    <div class="p-6 text-white/70 border-b border-white/25">
                        <p>Account Security</p>
                    </div>
                    <div class="text-white/70 p-6 text-sm">
                        <p class="mb-6 lg:mb-0">Two Factor Authentication</p>
                        <form action="{{ route('security.update') }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="lg:p-4">
                                <div>
                                    <label class="text-white/70" for="email">Enable 2FA</label> <br />
                                    <select
                                        class="bg-background outline-none p-3 mb-2 border border-white/30 w-full rounded-lg mt-2 h-[50px]">
                                        <option {{ !$user->twoFactorCode ? 'selected' : '' }}>OFF</option>
                                        <option {{ $user->twoFactorCode ? 'selected' : '' }}>ON</option>
                                    </select>
                                </div>

                                <div class="mt-2">
                                    @include('components.input-icon', [
                                        'label' => 'Enter 2FA Code',
                                        'name' => 'twoFactorCode',
                                        'icon' => '<i class="fa fa-qrcode fa-lg"></i>',
                                    ])
                                </div>

                                <button class="bg-orange p-3 rounded-lg w-full text-black mt-4">Change Password</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="w-full rounded-lg overflow-hidden bg-black my-6">
                    <div class="p-6 text-white/70 border-b border-white/25">
                        <p>Google Authenticator Guide</p>
                    </div>
                    <div class="text-white/70 p-6 text-sm">
                        <ul class="list-decimal px-6">
                            <li>Install Google Authenticator for Android or Apple and open Google Authenticator</li>
                            <li>Go to <span class="text-red-400">Menu</span> -> <span class="text-red-400">Setup
                                    Account</span>
                            </li>
                            <li>Choose <span class="text-red-400">Scan a barcode </span> option, and scan the barcode
                                shown
                                on
                                this page</li>
                            <li>If you are unable to scan the barcode: Choose <span class="text-red-400">Enter provided
                                    key</span> and type in the "Security Key"
                            </li>
                            <li>A six digit number will now appear in your Google Authenticator app home screen, enter
                                this
                                code
                            </li>
                            <li>into the 2FA form on this page</li>
                            <li>Every time you login to HSB FOREX TRADE you must enter the new 2FA code from your Google
                            </li>
                            <li>Authenticator into the 2FA box on the login form</li>
                            <li>Contact administrator if you want to reset your 2FA Google Authenticator.</li>
                        </ul>
                    </div>
                </div>
            </div>
        @endif

    </section>
@endsection
